# tag::client-secret[]
{{ range .Values.clients }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .name }}-secret"
stringData:
  client-id: {{ .id | quote }}
  client-secret: {{ .secret | quote }}
---
{{- end }}
# end::client-secret[]