# tag::keycloak-ingress[]
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "keycloak.fullname" . }}-ingress
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ include "keycloak.hostname" . }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "keycloak.fullname" . }}
            port:
              number: 8080
# end::keycloak-ingress[]