# tag::keycloak-secret[]
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-creds
stringData:
  admin-user: {{ .Values.admin.username }}
  admin-password: {{ .Values.admin.password }}
# end::keycloak-secret[]