# tag::service-binding[]
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name:
    spring-petclinic-keycloak
spec:
  services:
  - group: apps
    version: v1
    kind: Deployment
    name: {{ .Values.keycloak.name }}
  - group: ""
    version: v1
    kind: Secret
    name: petclinic-secret
  application:
    name: {{ .Values.petclinicapp.name }}
    group: apps
    version: v1
    resource: deployments
# end::service-binding[]
---
# tag::service-binding[]
apiVersion: binding.operators.coreos.com/v1alpha1
kind: ServiceBinding
metadata:
  name:
    spring-petclinic-postgresql
spec:
  services:
    - group: apps
      version: v1
      kind: Deployment
      name: {{ .Values.postgresql.name }}
  application:
    name: {{ .Values.petclinicapp.name }}
    group: apps
    version: v1
    resource: deployments
# end::service-binding[]

