# tag::db-secret[]
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
stringData:
  database: {{ .Values.secret.database }}
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
# end::db-secret[]