# tag::db-service[]
apiVersion: v1
kind: Service
metadata:
  name: {{ include "postgresql.fullname" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    {{- include "postgresql.selectorLabels" . | nindent 4 }}
# end::db-service[]